### ISSUE TITLE
Unable to get this to work with Sodium + Indium

### ISSUE THREAD

**Issue by Jademalo** [PepperCode1/ConnectedTexturesMod-Fabric#5]
Not sure why, but I can't get this to work with Sodium, Indium, FabricAPI, and ModMenu.

I've downloaded the recommended texture pack, and it has been enabled. I'm running JDK 15 to prevent a crash with the latest build of Sodium from the github actions artifacts. Connected Textures aren't disabled in the CTM options.
As far as I can tell, this should work.

![2021-02-23_19 17 45](https://user-images.githubusercontent.com/386846/108895735-e4c89300-760b-11eb-98e4-3d7a0e88c47f.png)
![2021-02-23_19 17 49](https://user-images.githubusercontent.com/386846/108895742-e5f9c000-760b-11eb-98ef-ebb334e8f41e.png)
![2021-02-23_19 17 52](https://user-images.githubusercontent.com/386846/108895751-e72aed00-760b-11eb-8d56-b400b8de598b.png)
![2021-02-23_19 17 57](https://user-images.githubusercontent.com/386846/108895755-e7c38380-760b-11eb-817f-0efa879efa5f.png)

**Comment by PepperCode1** [comment]
It looks like you're using the [pack for modded textures](https://www.curseforge.com/minecraft/texture-packs/modded-connected-ctm) instead of the [pack for vanilla textures](https://www.curseforge.com/minecraft/texture-packs/mc-connected-ctm). The modded one adds connected textures for other Forge mods, many of which don't exist on Fabric. The vanilla one is probably the one you want, so let me know if it works.

**Comment by Jademalo** [comment]
Yep, that's it. I feel dumb, lol.

![2021-02-24_01 45 39](https://user-images.githubusercontent.com/386846/108932917-13616080-7642-11eb-977b-9f97b6ee9509.png)

Sorry about the waste of time! Glad it was something simple.
I must've inadvertantly clicked it for my main window when I was opening the second tab for the pane fix pack, that's the only thing I can think. 

Thanks!
